---
abstract: 'A pure perl multi-level hash/array DBM that supports transactions'
author:
  - unknown
build_requires:
  File::Path: 0.01
  File::Temp: 0.01
  Pod::Usage: 1.3
  Test::Deep: 0.095
  Test::Exception: 0.21
  Test::More: 0.88
  Test::Warn: 0.08
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBM-Deep
no_index:
  directory:
    - utils
provides:
  DBM::Deep:
    file: lib/DBM/Deep.pm
    version: 2.0011
  DBM::Deep::Array:
    file: lib/DBM/Deep/Array.pm
    version: 0
  DBM::Deep::Engine:
    file: lib/DBM/Deep/Engine.pm
    version: 0
  DBM::Deep::Engine::DBI:
    file: lib/DBM/Deep/Engine/DBI.pm
    version: 0
  DBM::Deep::Engine::File:
    file: lib/DBM/Deep/Engine/File.pm
    version: 0
  DBM::Deep::Hash:
    file: lib/DBM/Deep/Hash.pm
    version: 0
  DBM::Deep::Iterator:
    file: lib/DBM/Deep/Iterator.pm
    version: 0
  DBM::Deep::Iterator::DBI:
    file: lib/DBM/Deep/Iterator/DBI.pm
    version: 0
  DBM::Deep::Iterator::File:
    file: lib/DBM/Deep/Iterator/File.pm
    version: 0
  DBM::Deep::Iterator::File::BucketList:
    file: lib/DBM/Deep/Iterator/File/BucketList.pm
    version: 0
  DBM::Deep::Iterator::File::Index:
    file: lib/DBM/Deep/Iterator/File/Index.pm
    version: 0
  DBM::Deep::Null:
    file: lib/DBM/Deep/Null.pm
    version: 0
  DBM::Deep::Sector:
    file: lib/DBM/Deep/Sector.pm
    version: 0
  DBM::Deep::Sector::DBI:
    file: lib/DBM/Deep/Sector/DBI.pm
    version: 0
  DBM::Deep::Sector::DBI::Reference:
    file: lib/DBM/Deep/Sector/DBI/Reference.pm
    version: 0
  DBM::Deep::Sector::DBI::Scalar:
    file: lib/DBM/Deep/Sector/DBI/Scalar.pm
    version: 0
  DBM::Deep::Sector::File:
    file: lib/DBM/Deep/Sector/File.pm
    version: 0
  DBM::Deep::Sector::File::BucketList:
    file: lib/DBM/Deep/Sector/File/BucketList.pm
    version: 0
  DBM::Deep::Sector::File::Data:
    file: lib/DBM/Deep/Sector/File/Data.pm
    version: 0
  DBM::Deep::Sector::File::Index:
    file: lib/DBM/Deep/Sector/File/Index.pm
    version: 0
  DBM::Deep::Sector::File::Null:
    file: lib/DBM/Deep/Sector/File/Null.pm
    version: 0
  DBM::Deep::Sector::File::Reference:
    file: lib/DBM/Deep/Sector/File/Reference.pm
    version: 0
  DBM::Deep::Sector::File::Scalar:
    file: lib/DBM/Deep/Sector/File/Scalar.pm
    version: 0
  DBM::Deep::Storage:
    file: lib/DBM/Deep/Storage.pm
    version: 0
  DBM::Deep::Storage::DBI:
    file: lib/DBM/Deep/Storage/DBI.pm
    version: 0
  DBM::Deep::Storage::File:
    file: lib/DBM/Deep/Storage/File.pm
    version: 0
requires:
  Digest::MD5: 1.00
  Fcntl: 0.01
  Scalar::Util: 1.14
  perl: 5.008_004
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/robkinyon/dbm-deep
version: 2.0011
